

server:
  port: 8844

logging:
  level:
    com.com.fenseaizi.wmstoredemo: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wmstore1?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
servlet:
  multipart:
    enabled: true
    max-file-size: 100MB
    max-request-size: 100MB
  http:
    multipart:
      enabled=true

